filters:
  - filter_type: dynamic
    file_format: PO
    source_language: en
    source_files_expression: src/sphinx_syft_theme/locale/en/LC_MESSAGES/<file>.po
    translation_files_expression: src/sphinx_syft_theme/locale/<lang>/LC_MESSAGES/<file>.po
