#######################################################################################
# Book settings
title: "Sphinx-Syft-Theme"
logo: _static/images/dummy_logo_dark.svg
author: The OpenMined Community
copyright: "2023"
email: callis@openmined.org
description: >- # this means to ignore newlines
  This is an example book built with Jupyter Books.

only_build_toc_files: true

execute:
  # See https://jupyterbook.org/content/execute.html
  execute_notebooks: cache
  #   "auto" should only execute those notebooks that don't have output in all cells.
  #   "force" : force execution of all notebooks
  #   "cache": Cache output of notebooks on each build.
  timeout: 800
  # Cells that are expected to fail (for pedagogical reasons) should set the cell tag `raises-exceptions`
  # allow_errors: False
  exclude_patterns:
  - README.md
  - sphinx_syft_theme
  - build/
  - dist/
  - setup.py
  - setup.cfg
  - pyproject.toml
  - PKG-INFO
  - MANIFEST.in
  - LICENSE
  - .gitignore
  # - *.egg-info

html:
  favicon: _static/images/favicon.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  use_download_button: true

repository:
  url: https://github.com/callezenwaka/sphinx-syft-theme
  branch: main
  path_to_book: docs

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

parse:
  myst_substitutions:
    sub3: My _global_ value!
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    html_theme: sphinx_syft_theme
    html_static_path:
      - _static
      # - _images
      # - images
    html_css_files:
      - css/syft.css
    html_theme_options:
      theme_hotjar_id: "YOUR_HOTJAR_ID"
      github_url: https://github.com/callezenwaka/sphinx-syft-theme
      twitter_url: https://twitter.com/callezenwaka
      repository_url: https://github.com/callezenwaka/sphinx-syft-theme
      # extra_navbar: Theme by <a href="https://openmined.org">OpenMined Syft</a>
      announcement: "⚠️The latest release is live here <a href='https://pypi.org/project/sphinx-syft-theme/0.2.6/' target: _blank>sphinx-syft-theme </a> ⚠️"
      logo:
        image_light: _static/images/dummy_logo_light.svg
        text: Theme # Uncomment to try text with logo
      # external_links:
      #   - url: https://github.com/callezenwaka/syft-theme
      #     name: GitHub
      #     external: True
      #     attributes:
      #       target: _blank
      navbar_links:
        - name: Documentation
          url: '/index.html'
        - name: About
          url: '/about.html'
        - name: Glossary
          url: '/glossary.html'
        # - name: GitHub
        #   url: https://github.com/callezenwaka/syft-theme
        #   external: True
        #   attributes:
        #     - target: _blank
      icon_links:
        - name: Blog
          url: https://blog.openmined.org
          icon: _static/favicon.ico
          type: local
      custom_image_paths:
        - "/_static/images/persona.png"
      custom_shortcode_to_image:
        "|:persona:|": "/_static/images/persona.png"
      # page_layouts:
      #   index: page-banner.html
      #   standalone: page-standalone.html
      footer_logos:
        logo1: _static/images/d_logo_dark.svg
        logo2: _static/images/d_logo_dark.svg
        logo3: _static/images/d_logo_dark.svg
      footer_menu:
        - title: "More about..."
          items:
            - name: OpenMined
              url: https://openmined.org/
            - name: OpenMined
              url: https://openmined.org/
            - name: OpenMined
              url: https://openmined.org/
    html_sidebars:
      # index: []
      # standalone: []
      '**':
        search-field.html
        sbt-sidebar-nav.html

  # Source suffix configuration
  source_suffix:
    - .rst: restructuredtext
    - .md: markdown

  extra_extensions:
    - ablog
    - sphinx_click.ext
    - sphinx_inline_tabs
    # - sphinx_tabs.tabs
    - sphinx.ext.autodoc
    - sphinx.ext.todo
    - sphinx.ext.autodoc
    - sphinx.ext.intersphinx
    - sphinxcontrib.bibtex
    # - sphinx_syft_theme.components.symoji
