#######################################################################################
# Book settings
title: ""
logo: images/logo-dark.svg
author: The OpenMined Community
copyright: "2023"
email: callis@openmined.org
description: >- # this means to ignore newlines
  This is an example book built with Jupyter Books.

execute:
  execute_notebooks: cache

html:
  favicon: images/favicon.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  use_download_button: true
  baseurl: https://openmined.org/

repository:
  url: https://github.com/callezenwaka/syft-theme
  branch: main
  path_to_book: docs

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

parse:
  myst_substitutions:
    sub3: My _global_ value!
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

bibtex_bibfiles:
  - reference/references.bib

sphinx:
  config:
    html_theme: sphinx_syft_theme
    html_theme_options:
      github_url: https://github.com/callezenwaka/syft-theme
      twitter_url: https://twitter.com/openmined
      repository_url: https://github.com/callezenwaka/syft-theme
      extra_navbar: Theme by <a href="https://openmined.org">OpenMined Syft</a>
      navbar_links:
        - name: Documentation
          url: 'index#documentation'
        - name: GitHub
          url: https://github.com/callezenwaka/syft-theme
          external: True
      page_layouts:
        index: page-banner.html
        standalone: page-standalone.html
      footer_logos:
        NCAR: images/NCAR-contemp-logo-blue.svg
        Unidata: images/Unidata_logo_horizontal_1200x300.svg
        UAlbany: images/UAlbany-A2-logo-purple-gold.svg
      footer_menu:
        - title: "More about..."
          items:
            - name: OpenMined
              url: https://openmined.org/
            - name: OpenMined
              url: https://openmined.org/
            - name: OpenMined
              url: https://openmined.org/
        - title: "Let us know..."
          items:
            - name: Submit an issue on GitHub
              url: https://github.com/callezenwaka/syft-theme/issues/new?title=Issue%20with%20Syft%20Theme&body=Your%20issue%20content%20here.
            - name: Feedback to OpenMined Syft
              url: https://openmined.org
        - title: "Join the community"
          items:
            - name: Contributor's Guide
              url: https://openmined.org
            - name: Our GitHub Organization
              url: https://github.com/callezenwaka
    html_sidebars:
      index: []
      standalone: []
      reference/blog/*:
        - sidebar-logo.html
        - search-field.html
        - postcard.html
        - recentposts.html
        - tagcloud.html
        - categories.html
        - archives.html
        - sbt-sidebar-nav.html
        - sbt-sidebar-footer.html
    blog_path: reference/blog
    blog_post_pattern: "reference/blog/*.md"
    blog_baseurl: "https://syftbook.readthedocs.io"
    fontawesome_included: True
    post_auto_image: 1
    post_auto_excerpt: 2

  extra_extensions:
    - ablog
    - sphinx_click.ext
    - sphinx_inline_tabs
    - sphinx_tabs.tabs
    - sphinx.ext.autodoc
    - sphinx.ext.todo
    - sphinx.ext.autodoc
    - sphinx.ext.intersphinx
    - sphinxcontrib.bibtex
